#!/usr/bin/env python3
"""Inject a tiny P07 probe into a P06-patched Tesseract checkout.

The probe is intentionally not a benchmark. It loads a real .stim circuit,
converts it to a detector error model using the same Stim ErrorAnalyzer call as
tesseract_trellis_main.cc, and constructs our patched Trellis decoder. A zero
exit status therefore means the real multi-observable DEM made it through the
actual public parser/constructor path.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

SOURCE = r'''// Generated by apply_p07_bb_constructor_probe.py.
#include <cstdio>
#include <exception>
#include <iostream>
#include <string>

#include "stim.h"
#include "tesseract_trellis.h"

using namespace tesseract_decoder;

int main(int argc, char** argv) {
  if (argc != 2) {
    std::cerr << "usage: p07_bb_probe CIRCUIT.stim\n";
    return 2;
  }
  const std::string path = argv[1];
  try {
    FILE* file = fopen(path.c_str(), "r");
    if (!file) {
      std::cerr << "could_not_open=" << path << "\n";
      return 3;
    }
    stim::Circuit circuit = stim::Circuit::from_file(file);
    fclose(file);

    stim::DetectorErrorModel dem = stim::ErrorAnalyzer::circuit_to_detector_error_model(
        circuit,
        /*decompose_errors=*/false,
        /*fold_loops=*/true,
        /*allow_gauge_detectors=*/true,
        /*approximate_disjoint_errors_threshold=*/1,
        /*ignore_decomposition_failures=*/false,
        /*block_decomposition_from_introducing_remnant_edges=*/false);

    const size_t num_detectors = dem.count_detectors();
    const size_t num_observables = dem.count_observables();
    if (num_observables < 2 || num_observables > 64) {
      std::cerr << "unexpected_observable_count=" << num_observables << "\n";
      return 4;
    }

    TesseractTrellisConfig config;
    config.dem = std::move(dem);
    config.beam_width = 15;
    config.beam_eps = 0.0;
    config.ranking_mode = TesseractTrellisRankingMode::MassOnly;
    config.merge_errors = true;
    config.verbose = false;
    config.track_kept_state_stats = false;

    TesseractTrellisDecoder decoder(std::move(config));
    if (decoder.num_observables != num_observables) {
      std::cerr << "decoder_observable_mismatch=" << decoder.num_observables
                << " expected=" << num_observables << "\n";
      return 5;
    }

    std::cout << "status=constructed"
              << " observables=" << num_observables
              << " detectors=" << num_detectors
              << " decoder_observables=" << decoder.num_observables
              << " beam=15"
              << " beam_eps=0"
              << " ranking=mass"
              << " circuit=" << path << "\n";
    return 0;
  } catch (const std::exception& ex) {
    std::cerr << "exception=" << ex.what() << " circuit=" << path << "\n";
    return 10;
  }
}
'''

BUILD_SNIPPET = r'''

# P07a: construction-only probe for pinned real bivariate-bicycle circuits.
# This is correctness/integration evidence, NOT a performance benchmark.
cc_binary(
    name = "p07_bb_probe",
    srcs = ["p07_bb_probe.cc"],
    copts = OPT_COPTS,
    linkopts = OPT_LINKOPTS,
    deps = [
        ":libtesseract_trellis",
        "@stim//:stim_lib",
    ],
)
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream-dir", required=True)
    ap.add_argument("--report", required=True)
    args = ap.parse_args()

    root = Path(args.upstream_dir)
    source_path = root / "src" / "p07_bb_probe.cc"
    build_path = root / "src" / "BUILD"
    if source_path.exists():
        raise RuntimeError(f"Refusing to overwrite existing {source_path}")
    build_text = build_path.read_text(encoding="utf-8")
    if 'name = "p07_bb_probe"' in build_text:
        raise RuntimeError("p07_bb_probe target already exists")
    if 'name = "libtesseract_trellis"' not in build_text:
        raise RuntimeError("Expected libtesseract_trellis target not found")

    source_path.write_text(SOURCE, encoding="utf-8")
    build_path.write_text(build_text.rstrip() + BUILD_SNIPPET + "\n", encoding="utf-8")

    report = {
        "phase": "P07a",
        "kind": "real-bb-constructor-probe",
        "kernel_changes": False,
        "decoder_cli_changes": False,
        "probe_only": True,
        "probe_target": "//src:p07_bb_probe",
        "probe_semantics": "Stim circuit -> detector error model -> patched Trellis constructor",
        "probe_config": {"beam": 15, "beam_eps": 0, "ranking": "mass", "merge_errors": True},
        "benchmark_valid": False,
        "timing_metrics_interpretable": False,
    }
    report_path = Path(args.report)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
