#!/usr/bin/env python3
"""Inject the P07b deterministic real-BB shot runner into a P06-patched checkout.

The generated binary samples exactly one shot from a real Stim circuit using a
caller-supplied seed, converts the circuit to a DEM exactly as the public
`tesseract_trellis_main.cc` does, decodes the detector syndrome with the P06
multi-observable library path, and emits machine-readable key=value evidence.

This is a correctness/integration smoke test, not a benchmark.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

SOURCE = r'''// Generated by apply_p07b_bb_shot_runner.py.
#include <cstdio>
#include <cstdint>
#include <exception>
#include <iostream>
#include <random>
#include <string>
#include <utility>

#include "stim.h"
#include "tesseract_trellis.h"

using namespace tesseract_decoder;

namespace {

uint64_t parse_seed(const char* text) {
  size_t pos = 0;
  const std::string value(text);
  const uint64_t seed = std::stoull(value, &pos, 10);
  if (pos != value.size()) {
    throw std::invalid_argument("seed contains non-decimal characters");
  }
  return seed;
}

void print_hits(const std::vector<uint64_t>& hits) {
  for (size_t k = 0; k < hits.size(); ++k) {
    if (k) std::cout << ',';
    std::cout << hits[k];
  }
}

}  // namespace

int main(int argc, char** argv) {
  if (argc != 3) {
    std::cerr << "usage: p07b_bb_shot_runner CIRCUIT.stim SEED\n";
    return 2;
  }
  const std::string path = argv[1];
  try {
    const uint64_t seed = parse_seed(argv[2]);

    FILE* file = fopen(path.c_str(), "r");
    if (!file) {
      std::cerr << "could_not_open=" << path << "\n";
      return 3;
    }
    stim::Circuit circuit = stim::Circuit::from_file(file);
    fclose(file);

    stim::DetectorErrorModel dem = stim::ErrorAnalyzer::circuit_to_detector_error_model(
        circuit,
        /*decompose_errors=*/false,
        /*fold_loops=*/true,
        /*allow_gauge_detectors=*/true,
        /*approximate_disjoint_errors_threshold=*/1,
        /*ignore_decomposition_failures=*/false,
        /*block_decomposition_from_introducing_remnant_edges=*/false);

    const size_t num_observables = dem.count_observables();
    const size_t num_detectors = circuit.count_detectors();
    if (num_observables < 2 || num_observables > 64) {
      std::cerr << "unexpected_observable_count=" << num_observables << "\n";
      return 4;
    }

    // Match the public CLI sampling route, but sample exactly one deterministic shot.
    std::mt19937_64 rng(seed);
    const auto [dets, obs] = stim::sample_batch_detection_events<64>(circuit, 1, rng);
    stim::simd_bit_table<64> obs_T = obs.transposed();
    stim::SparseShot shot;
    shot.clear();
    shot.obs_mask = obs_T[0];
    for (size_t d = 0; d < num_detectors; ++d) {
      if (dets[d][0]) {
        shot.hits.push_back(d);
      }
    }

    const uint64_t truth_mask = shot.obs_mask_as_u64();

    TesseractTrellisConfig config;
    config.dem = std::move(dem);
    config.beam_width = 15;
    config.beam_eps = 0.0;
    config.ranking_mode = TesseractTrellisRankingMode::MassOnly;
    config.merge_errors = true;
    config.verbose = false;
    config.track_kept_state_stats = true;

    TesseractTrellisDecoder decoder(std::move(config));
    decoder.decode_shot(shot.hits);
    const uint64_t predicted_mask = decoder.predicted_obs_mask;

    if (num_observables < 64) {
      const uint64_t allowed_mask = (uint64_t{1} << num_observables) - 1;
      if ((truth_mask & ~allowed_mask) != 0) {
        std::cerr << "truth_mask_out_of_range=" << truth_mask << "\n";
        return 5;
      }
      if ((predicted_mask & ~allowed_mask) != 0) {
        std::cerr << "predicted_mask_out_of_range=" << predicted_mask << "\n";
        return 6;
      }
    }

    // Deliberately no wall-clock field: GitHub runner timing is not benchmark evidence.
    std::cout << "status=decoded"
              << " seed=" << seed
              << " observables=" << num_observables
              << " detectors=" << num_detectors
              << " hits_count=" << shot.hits.size()
              << " truth_mask=" << truth_mask
              << " predicted_mask=" << predicted_mask
              << " low_confidence=" << (decoder.low_confidence_flag ? 1 : 0)
              << " states_expanded=" << decoder.num_states_expanded
              << " states_merged=" << decoder.num_states_merged
              << " max_beam=" << decoder.max_beam_size_seen
              << " frontier_width=" << decoder.max_frontier_width_seen
              << " syndrome=";
    print_hits(shot.hits);
    std::cout << '\n';
    return 0;
  } catch (const std::exception& ex) {
    std::cerr << "exception=" << ex.what() << " circuit=" << path << "\n";
    return 10;
  }
}
'''

BUILD_SNIPPET = r'''

# P07b: one deterministic real-BB shot through the patched multi-observable library.
# Integration/correctness smoke only; never interpret hosted-runner timing as a benchmark.
cc_binary(
    name = "p07b_bb_shot_runner",
    srcs = ["p07b_bb_shot_runner.cc"],
    copts = OPT_COPTS,
    linkopts = OPT_LINKOPTS,
    deps = [
        ":libtesseract_trellis",
        "@stim//:stim_lib",
    ],
)
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream-dir", required=True)
    ap.add_argument("--report", required=True)
    args = ap.parse_args()

    root = Path(args.upstream_dir)
    source_path = root / "src" / "p07b_bb_shot_runner.cc"
    build_path = root / "src" / "BUILD"
    if source_path.exists():
        raise RuntimeError(f"Refusing to overwrite existing {source_path}")
    build_text = build_path.read_text(encoding="utf-8")
    if 'name = "p07b_bb_shot_runner"' in build_text:
        raise RuntimeError("p07b_bb_shot_runner target already exists")
    if 'name = "libtesseract_trellis"' not in build_text:
        raise RuntimeError("Expected libtesseract_trellis target not found")

    source_path.write_text(SOURCE, encoding="utf-8")
    build_path.write_text(build_text.rstrip() + BUILD_SNIPPET.rstrip() + "\n", encoding="utf-8")

    report = {
        "phase": "P07b",
        "kind": "deterministic-real-bb-shot-runner",
        "kernel_changes": False,
        "decoder_cli_changes": False,
        "runner_only": True,
        "runner_target": "//src:p07b_bb_shot_runner",
        "sample_num_shots_per_invocation": 1,
        "runner_config": {
            "beam": 15,
            "beam_eps": 0,
            "ranking": "mass",
            "merge_errors": True,
        },
        "benchmark_valid": False,
        "timing_metrics_interpretable": False,
        "scientific_ler_valid": False,
    }
    report_path = Path(args.report)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
