#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--upstream-dir", required=True)
    parser.add_argument("--kind", choices=["ancestor", "modern"], required=True)
    parser.add_argument("--report", required=True)
    args = parser.parse_args()

    root = Path(args.upstream_dir)
    build_path = root / "src" / "BUILD"
    source_path = root / "src" / "tesseract_trellis_diff_dump.cc"
    report_path = Path(args.report)
    report_path.parent.mkdir(parents=True, exist_ok=True)

    ns = "using namespace tesseract_decoder;\n" if args.kind == "modern" else ""
    source_path.write_text(f'''// P06c differential result dumper.
// Generated by the research harness. Not an upstream source file.
#include "tesseract_trellis.h"

#include <cstdio>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "stim.h"

{ns}

std::vector<uint64_t> parse_detections(const std::string& text) {{
  std::vector<uint64_t> out;
  if (text.empty() || text == "-") {{
    return out;
  }}
  std::stringstream ss(text);
  std::string token;
  while (std::getline(ss, token, ',')) {{
    if (!token.empty()) {{
      out.push_back(std::stoull(token));
    }}
  }}
  return out;
}}

int main(int argc, char** argv) {{
  if (argc != 3) {{
    std::cerr << "usage: tesseract_trellis_diff_dump MANIFEST_TSV OUTPUT_TSV\\n";
    return 2;
  }}

  std::ifstream manifest(argv[1]);
  if (!manifest) {{
    std::cerr << "could not open manifest: " << argv[1] << "\\n";
    return 2;
  }}
  std::ofstream output(argv[2]);
  if (!output) {{
    std::cerr << "could not open output: " << argv[2] << "\\n";
    return 2;
  }}

  output << "case_id\\tstatus\\tnum_observables\\tpredicted_obs_mask\\tlow_confidence\\n";
  std::string line;
  size_t line_number = 0;
  while (std::getline(manifest, line)) {{
    ++line_number;
    if (line.empty() || line[0] == '#') {{
      continue;
    }}
    std::vector<std::string> fields;
    std::stringstream ls(line);
    std::string field;
    while (std::getline(ls, field, '\\t')) {{
      fields.push_back(field);
    }}
    if (fields.size() != 4) {{
      std::cerr << "bad manifest line " << line_number << ": expected 4 TSV fields\\n";
      return 2;
    }}

    const std::string& case_id = fields[0];
    const std::string& dem_path = fields[1];
    const auto detections = parse_detections(fields[2]);
    const size_t beam_width = std::stoull(fields[3]);

    try {{
      FILE* file = std::fopen(dem_path.c_str(), "r");
      if (file == nullptr) {{
        throw std::runtime_error("could not open DEM " + dem_path);
      }}
      stim::DetectorErrorModel dem = stim::DetectorErrorModel::from_file(file);
      std::fclose(file);

      TesseractTrellisConfig config;
      config.dem = std::move(dem);
      config.beam_width = beam_width;
      config.beam_eps = 0.0;
      config.ranking_mode = TesseractTrellisRankingMode::MassOnly;

      TesseractTrellisDecoder decoder(std::move(config));
      decoder.decode_shot(detections);
      output << case_id << "\\tOK\\t" << decoder.num_observables << "\\t"
             << decoder.predicted_obs_mask << "\\t"
             << (decoder.low_confidence_flag ? 1 : 0) << "\\n";
    }} catch (const std::exception& ex) {{
      output << case_id << "\\tERROR:" << ex.what() << "\\t-\\t-\\t-\\n";
    }}
  }}
  return 0;
}}
''')

    build = build_path.read_text()
    if 'name = "tesseract_trellis_diff_dump"' in build:
        raise RuntimeError("P06c differential driver target already exists")
    build += r'''

cc_binary(
    name = "tesseract_trellis_diff_dump",
    srcs = ["tesseract_trellis_diff_dump.cc"],
    copts = OPT_COPTS,
    linkopts = OPT_LINKOPTS,
    deps = [
        ":libtesseract_trellis",
        "@stim//:stim_lib",
    ],
)
'''
    build_path.write_text(build)

    report = {
        "phase": "P06c",
        "kind": "differential-dump-driver",
        "target": args.kind,
        "fields": ["case_id", "status", "num_observables", "predicted_obs_mask", "low_confidence"],
        "benchmark_valid": False,
        "timing_metrics_interpretable": False,
    }
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
